/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asecave_Console_Color */

#ifndef _Included_com_asecave_Console_Color
#define _Included_com_asecave_Console_Color
#ifdef __cplusplus
extern "C" {
#endif
#undef com_asecave_Console_Color_BLACK
#define com_asecave_Console_Color_BLACK 0L
#undef com_asecave_Console_Color_RED
#define com_asecave_Console_Color_RED 1L
#undef com_asecave_Console_Color_YELLOW
#define com_asecave_Console_Color_YELLOW 2L
#undef com_asecave_Console_Color_GREEN
#define com_asecave_Console_Color_GREEN 3L
#undef com_asecave_Console_Color_CYAN
#define com_asecave_Console_Color_CYAN 4L
#undef com_asecave_Console_Color_BLUE
#define com_asecave_Console_Color_BLUE 5L
#undef com_asecave_Console_Color_PURPLE
#define com_asecave_Console_Color_PURPLE 6L
#undef com_asecave_Console_Color_DARK_RED
#define com_asecave_Console_Color_DARK_RED 7L
#undef com_asecave_Console_Color_GOLD
#define com_asecave_Console_Color_GOLD 8L
#undef com_asecave_Console_Color_DARK_GREEN
#define com_asecave_Console_Color_DARK_GREEN 9L
#undef com_asecave_Console_Color_DARK_CYAN
#define com_asecave_Console_Color_DARK_CYAN 10L
#undef com_asecave_Console_Color_DARK_BLUE
#define com_asecave_Console_Color_DARK_BLUE 11L
#undef com_asecave_Console_Color_DARK_PURPLE
#define com_asecave_Console_Color_DARK_PURPLE 12L
#undef com_asecave_Console_Color_DARK_GRAY
#define com_asecave_Console_Color_DARK_GRAY 13L
#undef com_asecave_Console_Color_GRAY
#define com_asecave_Console_Color_GRAY 14L
#undef com_asecave_Console_Color_WHITE
#define com_asecave_Console_Color_WHITE 15L
#ifdef __cplusplus
}
#endif
#endif
