/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asecave_Console */

#ifndef _Included_com_asecave_Console
#define _Included_com_asecave_Console
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_asecave_Console
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_asecave_Console_open
  (JNIEnv *, jobject);

/*
 * Class:     com_asecave_Console
 * Method:    start
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_asecave_Console_start
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_asecave_Console
 * Method:    setCursor
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_com_asecave_Console_setCursor
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     com_asecave_Console
 * Method:    fill
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_asecave_Console_fill__C
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_asecave_Console
 * Method:    fill
 * Signature: (CIIII)V
 */
JNIEXPORT void JNICALL Java_com_asecave_Console_fill__CIIII
  (JNIEnv *, jobject, jchar, jint, jint, jint, jint);

/*
 * Class:     com_asecave_Console
 * Method:    print
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_asecave_Console_print__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_asecave_Console
 * Method:    print
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_asecave_Console_print__C
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_asecave_Console
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_asecave_Console_print__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_asecave_Console
 * Method:    setColorCode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_asecave_Console_setColorCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_asecave_Console
 * Method:    getConsoleWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_asecave_Console_getConsoleWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_asecave_Console
 * Method:    getConsoleHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_asecave_Console_getConsoleHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_asecave_Console
 * Method:    setCursorVisible
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_asecave_Console_setCursorVisible
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_asecave_Console
 * Method:    setTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_asecave_Console_setTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_asecave_Console
 * Method:    getInputChar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_asecave_Console_getInputChar
  (JNIEnv *, jobject);

/*
 * Class:     com_asecave_Console
 * Method:    setFontSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_asecave_Console_setFontSize
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
