/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asecave_Console_FontSize */

#ifndef _Included_com_asecave_Console_FontSize
#define _Included_com_asecave_Console_FontSize
#ifdef __cplusplus
extern "C" {
#endif
#undef com_asecave_Console_FontSize_SMALL
#define com_asecave_Console_FontSize_SMALL 0L
#undef com_asecave_Console_FontSize_NORMAL
#define com_asecave_Console_FontSize_NORMAL 1L
#undef com_asecave_Console_FontSize_LARGE
#define com_asecave_Console_FontSize_LARGE 2L
#ifdef __cplusplus
}
#endif
#endif
